### ISSUE TITLE
Test for Log File Size - Incorrect LogFileSizePercentage calculation

### ISSUE THREAD

**Issue by SteveCInVA** [dataplat/dbachecks#868]
## Bug Report
In the test LogfileSize, the configuration value is expressed as a percentage yet, when applied to the calculation is expressed as an integer.

### Steps to Reproduce
Using default configuration get-dbcConfigValue polcy.database.logfilesizepercentage = 100.
Test states $LogFileSize | Should - BeLessThan ($DataFileSize * $LogFileSizePercentage).

This incorrectly calculates the allowed log log file size as 100 times the size of the datafile.  

Test should be $LogFileSize | Should - BeLessThan ($DataFileSize * ($LogFileSizePercentage/100.0)).

**Comment by SQLDBAWithABeard** [comment]
Dang, you are right - thank you
