### ISSUE TITLE
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 3

### ISSUE THREAD

**Issue by eliassal** [dataplat/dbachecks#873]
Hi, I am new to this tool, I did the following today

Install-Module PSFramework
Install-Module dbatools -Force
Install-Module dbachecks

I ran it against 2 SQL servers but got the following

> Tests Passed: 297, Failed: 15, Skipped: 306, Pending: 0, Inconclusive: 0
> WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 3.
> [18:31:57][Update-DbcPowerBiDataSource] Wrote results to C:\WINDOWS\temp\dbachecks\dbachecks_1_Default__CIS.json

### General Troubleshooting steps
- [ X] Verified running the latest release of dbachecks? 

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`
`Yes , I get 2.0.16`

- [X ] Verified errors are not related to permissions?
- [ yes] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): win 10 20H2
 - PowerShell Version: PS 7.2
 - SQL Server (Edition|Version): SQL2K16 Developer

### Steps to Reproduce
`1 - Invoke-DbcCheck -SqlInstance $SQLInstance –ComputerName $SQLInstance -Tag CIS -Show Summary -PassThru | Update-DbcPowerBiDataSource`

![dbaCheck](https://user-images.githubusercontent.com/8447864/152212627-54071abf-6c29-449a-add7-a82353703c69.jpg)

Thanks for your help

**Comment by eliassal** [comment]
HI, what should I do please? should I update the file manually, if yes, where I find the file?

**Comment by eliassal** [comment]
OK Thanks for the recommandation, so I need to update dbchecks using powershell, is this correct?

**Comment by SQLDBAWithABeard** [comment]
Yes
`Update-Module dbachecks`

will get the latest version and it is best to use a new PowerShell process once you have updated

````
Set-DbcConfig -Name app.sqlinstance -Value sql2k12, sql2k17, SQL2K12\SC2K12
Set-DbcConfig -Name app.computername -Value sql2k12, sql2k17, SQL2K12
$checks = 'InstanceConnection','DatabaseExists' # LIst of checks you want
$InstanceToStore = 'HOST/INSTANCE' # the instance that will hold the results
$databaseToStore = 'TheDatabase' # where will results be stored - two tables will be created
$Label = 'Production-CIS' # the label that you wish to give this set of tests

Invoke-DbcCheck -Check $checks | Convert-DbcResult -Label $label | Write-DbcTable -SqlInstance $InstanceToStore -Database $databaseToStore 
````
