### ISSUE TITLE
PowerBi report not showing instance name and other issues

### ISSUE THREAD

**Issue by eliassal** [dataplat/dbachecks#874]
## Bug Report
Hi, I am new to this tool, I did the following today

```
Install-Module PSFramework
Install-Module dbatools -Force
Install-Module dbachecks

```
I ran it against 2 SQL servers but got the following, then issued 

`Start-DbcPowerBi`

Power BI opens but Environment panel contains 
Production and Test
so where they do come from or how can this be linked to my instances?

2nd in the instances, there is a name which does not correspond to my instances names and I think that the rsport is for only the last run not for both instances.

Thanks for you help.

### General Troubleshooting steps
- [ X] Verified running the latest release of dbachecks? 

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`

> Yes , I get 2.0.16

- [X ] Verified errors are not related to permissions?
- [X ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): win 10 20H2
 - PowerShell Version: PS 7.2
 - SQL Server (Edition|Version): SQL2K16 Developer

### Steps to Reproduce
1 - Start-DbcPowerBi
![dbaCheck_002](https://user-images.githubusercontent.com/8447864/152214675-8ec6c890-ba15-4fe0-a823-0dbdd1ebed6f.jpg)

So the last question, how I can run dbacheck against several instances and having results in the same file so in PowerBI I can have hte 3 instances?

**Comment by eliassal** [comment]
PLEASE ignore this thread as it works fine the report after refreshing

**Comment by ClaudioESSilva** [comment]
Hi @eliassal glad you could solve it. 
Let us know if you have any other question
